name: Docs

on:
  workflow-dispatch:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: > 
        sudo apt install dia doxygen graphviz mscgen texlive perl

    - name: Generate
      run: |
        cmake -B build -S .
        cmake --build build -t doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/html
