name: Publish Doxygen Docs

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch_tags: true
        fetch-depth: 0

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: dia doxygen graphviz mscgen

    - name: Generate
      run: |
        cmake -B build -S .
        cmake --build build -t doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build/doc/html
