name: Publish Doxygen Docs

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch_tags: true
        fetch-depth: 0

    - uses: ssciwr/doxygen-install@v1

    - name: Generate Docs
      run: |
        cmake -B build -S .
        cmake --build build -t doc

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/html
